const GET_ALL_COMMENTS = `SELECT * FROM HR.COMMENTS`;
const ADD_COMMENT = `INSERT INTO COMMENTS(POST_ID, COMMENTED_BY, COMMENT_TEXT) VALUES(:1,:2,:3)`;
const DELETE_COMMENTS = 'DELETE FROM HR.COMMENTS WHERE POST_ID = :1';

module.exports = {GET_ALL_COMMENTS, ADD_COMMENT, DELETE_COMMENTS};