const CREATE_POST = `INSERT INTO HR.POSTS(POST_TITLE, POST_BODY, PHOTO, POSTED_BY, POSTED_BY_NAME,POST_ID) VALUES(:1,:2,:3,:4,:5,POST_ID.NEXTVAL)`;
const GET_ALL_POSTS = `SELECT POST_TITLE,POST_BODY, PHOTO,POSTED_BY, POSTED_BY_NAME,posts.POST_ID, COUNT(LIKED_BY) FROM posts LEFT OUTER JOIN likes ON posts.POST_ID = likes.POST_ID GROUP by posts.post_id,post_title,POST_BODY, PHOTO,POSTED_BY, POSTED_BY_NAME ORDER BY posts.POST_ID DESC`;
const GET_POST = `SELECT POST_TITLE,POST_BODY, PHOTO,POSTED_BY, POSTED_BY_NAME,posts.POST_ID, COUNT(LIKED_BY) FROM posts LEFT OUTER JOIN likes ON posts.POST_ID = likes.POST_ID WHERE POSTS.POST_ID = :1 GROUP by posts.post_id,post_title,POST_BODY, PHOTO,POSTED_BY, POSTED_BY_NAME`;
const GET_FOLLOWING_USER_POSTS = 'SELECT POST_TITLE,POST_BODY, PHOTO,POSTED_BY, POSTED_BY_NAME,posts.POST_ID, COUNT(LIKED_BY) FROM posts LEFT OUTER JOIN likes ON posts.POST_ID = likes.POST_ID WHERE POSTED_BY IN(SELECT FOLLOWING FROM FOLLOW WHERE USER_EMAIL = :1) GROUP by posts.post_id,post_title,POST_BODY, PHOTO,POSTED_BY, POSTED_BY_NAME ORDER BY posts.POST_ID DESC';

const GET_MY_POSTS = 'SELECT * FROM HR.POSTS WHERE POSTED_BY = :1';

const LIKE_POST = 'INSERT INTO HR.LIKES(POST_ID,LIKED_BY) VALUES(:1,:2)';
const UNLIKE_POST = 'DELETE FROM HR.LIKES WHERE POST_ID = :1 AND LIKED_BY = :2';
const LIKED_USERS = `SELECT * FROM HR.LIKES GROUP BY POST_ID, LIKED_BY`;
const LIKED_USERS_LIKE_UNLIKE = `SELECT * FROM HR.LIKES WHERE POST_ID=:1 AND LIKED_BY=:2 GROUP BY POST_ID, LIKED_BY`;
const DELETE_LIKES = `DELETE FROM HR.LIKES WHERE POST_ID = :1`;
const DELETE_POST = `DELETE FROM HR.POSTS WHERE POST_ID = :1`;


module.exports = {CREATE_POST, GET_ALL_POSTS, GET_MY_POSTS,LIKE_POST,UNLIKE_POST,GET_POST,LIKED_USERS, LIKED_USERS_LIKE_UNLIKE,DELETE_LIKES, DELETE_POST,GET_FOLLOWING_USER_POSTS};