// const INSERT_USER = 'INSERT INTO HR.USERS VALUES(:1, :2, :3)';
const INSERT_USER_WITHOUT_PIC = 'INSERT INTO HR.USERS(USER_EMAIL,USER_NAME,USER_PASSWORD) VALUES(:1, :2, :3)';
const INSERT_USER_WITH_PIC = 'INSERT INTO HR.USERS(USER_EMAIL,USER_NAME,USER_PASSWORD,PROFILE_PIC) VALUES(:1, :2, :3, :4)';
const USER_EXIST = 'SELECT * FROM HR.USERS WHERE USER_EMAIL = :1';
const GET_FOLLOWERS = `SELECT FOLLOWERS FROM HR.FOLLOW WHERE USER_EMAIL = :1`;
const GET_FOLLOWING = `SELECT FOLLOWING FROM HR.FOLLOW WHERE USER_EMAIL = :1`;
const INSERT_FOLLOWER = 'INSERT INTO FOLLOW(USER_EMAIL,FOLLOWERS) VALUES(:1,:2)';
const INSERT_FOLLOWING = 'INSERT INTO FOLLOW(USER_EMAIL,FOLLOWING) VALUES(:1,:2)';
const DELETE_FOLLOWER = `DELETE FROM FOLLOW WHERE USER_EMAIL = :1 AND FOLLOWERS = :2`;
const DELETE_FOLLOWING = `DELETE FROM FOLLOW WHERE USER_EMAIL = :1 AND FOLLOWING = :2`;
const UPDATE_PROFILE_PIC = `UPDATE USERS SET PROFILE_PIC = :1 WHERE USER_EMAIL = :2`;
const SEARCH_USER = `SELECT * FROM USERS WHERE USER_EMAIL LIKE :1`;
const GET_PROFILE_PICS = `SELECT USER_EMAIL, PROFILE_PIC FROM USERS`;

module.exports = {INSERT_USER_WITHOUT_PIC, INSERT_USER_WITH_PIC, USER_EXIST,GET_FOLLOWERS,GET_FOLLOWING,INSERT_FOLLOWER,INSERT_FOLLOWING,DELETE_FOLLOWER,DELETE_FOLLOWING,UPDATE_PROFILE_PIC,SEARCH_USER,GET_PROFILE_PICS}